### ISSUE TITLE
How to make childViewController lazy load

### ISSUE THREAD

**Issue by Rakutou** [y-hryk/YSLContainerViewController#12]
All " [ [UIViewControll alloc] init]" will  previously call "viewDidLoad" ,it is not good. Can you resolve this?

**Comment by Rakutou** [comment]
hi , <YSLContainerViewController.m> In viewDidLoad, I remove this code:
// ContentViewController setup
    for (int i = 0; i < self.childControllers.count; i++) {
        id obj = [self.childControllers objectAtIndex:i];
        if ([obj isKindOfClass:[UIViewController class]]) {
            UIViewController _controller = (UIViewController_)obj;
            CGFloat scrollWidth = _contentScrollView.frame.size.width;
            CGFloat scrollHeght = _contentScrollView.frame.size.height;
            controller.view.frame = CGRectMake(i \* scrollWidth, 0, scrollWidth, scrollHeght);
            [_contentScrollView addSubview:controller.view];
        }
    }
And I change the code :
- (void)setChildViewControllerWithCurrentIndex:(NSInteger)currentIndex
  {
  for (int i = 0; i < self.childControllers.count; i++) {
      id obj = self.childControllers[i];
      if ([obj isKindOfClass:[UIViewController class]]) {
          UIViewController _controller = (UIViewController_)obj;
          if (i == currentIndex) {
              [self addChildViewController:controller];
              [controller willMoveToParentViewController:self];
              CGFloat scrollWidth = _contentScrollView.frame.size.width;
              CGFloat scrollHeght = _contentScrollView.frame.size.height;
              controller.view.frame = CGRectMake(i \* scrollWidth, 0, scrollWidth, scrollHeght);
              [self.contentScrollView addSubview:controller.view];
              [controller didMoveToParentViewController:self];
  
  ```
      } else {
          [controller willMoveToParentViewController:self];
          [controller removeFromParentViewController];
          [controller didMoveToParentViewController:self];
      }
  }
  ```
  
  }
  }

that is it ,viewDidLoad just call at a time,further more,at first of time, childViewController just load fisrt one,then,tapped the title or slided the container load next.:)

**Comment by lupugabriel** [comment]
great!

**Comment by lupugabriel** [comment]
when u will release a new version? with this change?
